# Replace 'path/to/Project.xcodeproj' with the actual path to your Xcode project file
project '/Users/shantaliaz/Desktop/Xcode Projects/HerbSampleApp/HerbSampleApp.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/supabase-community/supabase-swift.git'

platform :ios, '14.0'

target 'HerbSampleApp' do
  use_frameworks!
  pod 'Supabase', '~> 1.0'
end

